# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea0c9e91d1905579fd1ce0443dbe66252d4ffc39f5ff0f0912dc15b264b26013ed8e24ae8faf4054dcaabb64417e05b37caa4ecfad74589f38cb63135c7973e

test:
  secret_key_base: 57eb568faba8049d3dbdc3131b2f162c7b88119d32055d82570a0ef098996e9bf06fe7a61a38e1ec9402cec60ac121cba8029106084cc47123b30517601f4cce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
